### ISSUE TITLE
Validateur supports CLJS

### ISSUE THREAD

**Issue by michaelklishin** [emrehan/clojurescript-awesome#2]
I'm not sure if this repository assumes any kind of external contributions since it is curated, but [Validateur](http://clojurevalidations.info/) and a pretty high quality validation library that supports ClojureScript.

**Comment by emrehan** [comment]
Hi,

I welcome all contributions. Validateur seems nice could you please add it to the list?

**Comment by emrehan** [comment]
I've added Validateur to the list, thanks :)
